version: '3.8'

services:
  crm:
    build:
      context: .
    container_name: crm
    env_file:
      - .env
    depends_on:
      - userdb
    networks:
      - backend-network
    ports:
      - "${APP_PORT}:8080"


  userdb:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data_user:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres_data_user:

networks:
  backend-network:
    driver: bridge
